version: '0.2'
language: en
useGitignore: true

ignorePaths:
  - '**/dist/**'
  - '**/node_modules/**'
  - pnpm-lock.yaml
  - target/**

words:
  - elif
  - esm
  - libwebkit
  - oxlint
  - pacman
  - pnpm
  - Rolldown
  - sandboxed
  - Tauri
  - tsdown
  - unrtel
  - WebKitGTK
  - WebView
  - WKWebView
  - Xvfb
