catalogMode: prefer
minimumReleaseAge: 1
fetchTimeout: 600000
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - examples/**
  - packages/**
  - '!**/dist/**'

catalog:
  '@antfu/eslint-config': ^8.2.0
  '@moeru/eslint-config': ^0.1.0-beta.18
  cspell: ^10.0.1
  eslint: ^10.5.0
  eslint-plugin-oxlint: ^1.73.0
  jiti: ^2.7.0
  knip: ^6.27.0
  oxlint: ^1.74.0
  taze: ^19.14.1
  tsdown: 0.22.14
  typescript: 5.9.3
