export const builtinModules = {
  'node:assert': './src/modules/assert/index.ts',
  'node:assert/strict': './src/modules/assert/strict.ts',
  'node:buffer': './src/modules/buffer/index.ts',
  'node:child_process': './src/modules/child_process/index.ts',
  'node:console': './src/modules/console/index.ts',
  'node:constants': './src/modules/constants/index.ts',
  'node:crypto': './src/modules/crypto/index.ts',
  'node:dgram': './src/modules/dgram/index.ts',
  'node:diagnostics_channel': './src/modules/diagnostics_channel/index.ts',
  'node:dns': './src/modules/dns/index.ts',
  'node:dns/promises': './src/modules/dns/promises.ts',
  'node:domain': './src/modules/domain/index.ts',
  'node:events': './src/modules/events/index.ts',
  'node:fs': './src/modules/fs/index.ts',
  'node:fs/promises': './src/modules/fs/promises.ts',
  'node:http': './src/modules/http/index.ts',
  'node:https': './src/modules/https/index.ts',
  'node:internal/ops': './src/internal/ops.ts',
  'node:module': './src/modules/module/index.ts',
  'node:net': './src/modules/net/index.ts',
  'node:os': './src/modules/os/index.ts',
  'node:path': './src/modules/path/index.ts',
  'node:path/posix': './src/modules/path/posix.ts',
  'node:path/win32': './src/modules/path/win32.ts',
  'node:perf_hooks': './src/modules/perf_hooks/index.ts',
  'node:process': './src/modules/process/index.ts',
  'node:punycode': './src/modules/punycode/index.ts',
  'node:querystring': './src/modules/querystring/index.ts',
  'node:readline': './src/modules/readline/index.ts',
  'node:readline/promises': './src/modules/readline/promises.ts',
  'node:repl': './src/modules/repl/index.ts',
  'node:stream': './src/modules/stream/index.ts',
  'node:stream/consumers': './src/modules/stream/consumers.ts',
  'node:stream/promises': './src/modules/stream/promises.ts',
  'node:stream/web': './src/modules/stream/web.ts',
  'node:string_decoder': './src/modules/string_decoder/index.ts',
  'node:sys': './src/modules/sys/index.ts',
  'node:timers': './src/modules/timers/index.ts',
  'node:timers/promises': './src/modules/timers/promises.ts',
  'node:tls': './src/modules/tls/index.ts',
  'node:tty': './src/modules/tty/index.ts',
  'node:url': './src/modules/url/index.ts',
  'node:util': './src/modules/util/index.ts',
  'node:util/types': './src/modules/util/types.ts',
  'node:worker_threads': './src/modules/worker_threads/index.ts',
  'node:zlib': './src/modules/zlib/index.ts',
} as const

export const builtinEntries = Object.fromEntries(
  Object.entries(builtinModules).map(([specifier, source]) => [specifier.slice('node:'.length), source]),
)

export const builtinManifest = Object.fromEntries(
  Object.keys(builtinModules).map(specifier => [specifier, `${specifier.slice('node:'.length)}.mjs`]),
)
